site_name: FIAE Umschulung Notes
docs_dir: notes
site_dir: site

theme:
  name: material

plugins:
  - search
  - tags
  - gen-files:
      scripts:
        - scripts/gen_indexes.py
  - awesome-pages

markdown_extensions:
  - meta
  - toc:
      permalink: true
