site_name: FIAE Umschulung Notes
docs_dir: notes
site_dir: site

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate

  palette:
    - scheme: default
      primary: white
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Wechsel zu Dunkelmodus

    - scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Wechsel zu Hellmodus

  font:
    text: Inter
    code: JetBrains Mono

plugins:
  - search
  - tags
  - gen-files:
      scripts:
        - scripts/gen_indexes.py
  - awesome-pages

markdown_extensions:
  - meta
  - admonition
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - toc:
      permalink: true

extra_css:
  - stylesheets/extra.css
